export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_API_KEY = 'INVALID_API_KEY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
